=== ERROR at 2025-08-17T22:30:52.729238 ===
Logger: infrastructure.caching.redis_cache
Module: redis_cache
Function: _get_redis() at line 90
Thread: MainThread (8324735168)
Process: MainProcess (19479)
Message: Failed to connect to Redis: Error Multiple exceptions: [Errno 61] Connect call failed ('::1', 6379, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 6379) connecting to localhost:6379.
Context:
  taskName: Task-2
==================================================
